services:
  router:
    build: router
    restart: always
    init: true
    ports:
    - 80:80
    - 443:443
    links:
    - website:website
    - spaceage-website:spaceage-website
    - prosody:prosody
    extra_hosts:
    - host.docker.internal:host-gateway
    dns:
    - 108.61.10.10
    networks:
      default:
        ipv4_address: 172.18.100.1
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    ports:
      - 10.99.10.1:8384:8384
      - 22000:22000
      - 22000:22000/udp
    dns:
    - 108.61.10.10
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
    - syncthing_config:/config
    - syncthing_data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s
  website:
    image: ghcr.io/doridian/website/website:latest
    restart: always
    dns:
    - 108.61.10.10
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - website_config:/config
    - website_data:/data
  spaceage-website:
    image: ghcr.io/spaceagemp/website/website:latest
    restart: always
    dns:
    - 108.61.10.10
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - spaceage_website_config:/config
    - spaceage_website_data:/data
  prosody:
    build: prosody
    restart: always
    dns:
    - 108.61.10.10
    ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
    - 5281:5281
    environment:
      DOMAIN: f0x.es
    volumes:
    - prosody_config:/etc/prosody
    - prosody_letsencrypt:/etc/letsencrypt
  autoheal:
    restart: always
    userns_mode: host
    image: ghcr.io/doridian/dockerheal/dockerheal:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  syncthing_config: {}
  syncthing_data: {}

  website_config: {}
  website_data: {}

  spaceage_website_config: {}
  spaceage_website_data: {}

  prosody_config: {}
  prosody_letsencrypt: {}

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdd8:2357:cb1b:acf4::/64
          gateway: fdd8:2357:cb1b:acf4::1
        - subnet: 172.18.0.4/16
          gateway: 172.18.0.1
