services:
  router:
    build: router
    restart: always
    init: true
    ports:
    - 80:80
    - 443:443
    links:
    - website:website
    extra_hosts:
    - host.docker.internal:host-gateway
    dns:
    - 108.61.10.10
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    ports:
      - 10.99.10.1:8384:8384
      - 22000:22000
      - 22000:22000/udp
    dns:
    - 108.61.10.10
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
    - syncthing_config:/config
    - syncthing_data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s
  website:
    image: ghcr.io/doridian/website/website:latest
    restart: always
    dns:
    - 108.61.10.10
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - website_config:/config
    - website_data:/data
  spaceage-website:
    image: ghcr.io/spaceagemp/website/website:latest
    restart: always
    dns:
    - 108.61.10.10
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - website_config:/config
    - website_data:/data
  autoheal:
    restart: always
    userns_mode: host
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  syncthing_config: {}
  syncthing_data: {}
  website_config: {}
  website_data: {}

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdd8:2357:cb1b:acf4::/64
          gateway: fdd8:2357:cb1b:acf4::1
