services:
  router:
    build: router
    restart: always
    init: true
    ports:
    - 80:80
    - 443:443
    links:
    - webdav:webdav
    extra_hosts:
    - host.docker.internal:host-gateway
    - webdav:webdav
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    ports:
      - 8384:8384
      - 22000:22000
      - 22000:22000/udp
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s
  webdav:
    build: webdav
    restart: always
    init: true
    environment:
      WEBDAV_PASSWORD_DORIDIAN: ${WEBDAV_PASSWORD_DORIDIAN}
    volumes:
     - webdav_config:/config
     - webdav_data:/data
     - syncthing_data:/syncthing
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
  autoheal:
    restart: always
    userns_mode: host
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  syncthing_config: {}
  syncthing_data: {}
  webdav_config: {}
  webdav_data: {}

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdd8:2357:cb1b:acf4::/64
          gateway: fdd8:2357:cb1b:acf4::1
