defaults:
  ports:
    http: 80
    https: 443
aliases:
  nas:
    target: 10.2.11.1
  grafana:
    target: 10.2.11.5
  homeassistant:
    target: 10.2.12.2
  spaceage-web:
    target: 10.3.10.5
  foxcaves:
    target: 10.3.10.1
  tasks:
    target: 10.3.10.8
hosts:
  __default__:
    target: 127.0.0.1
    ports:
      http: 8080
      https: 8443
  grafana.foxden.network:
    target: grafana
  nas.foxden.network:
    target: nas
  homeassistant.foxden.network:
    target: homeassistant
  tasks.foxden.network:
    target: tasks
  syncthing.doridian.net:
    target: webdav
  api.spaceage.mp:
    target: spaceage-web
  spaceage.mp:
    target: spaceage-web
  static.spaceage.mp:
    target: spaceage-web
  tts.spaceage.mp:
    target: spaceage-web
  www.spaceage.mp:
    target: spaceage-web
  forums.spaceage.mp:
    target: spaceage-web
  foxcav.es:
    target: foxcaves
  www.foxcav.es:
    target: foxcaves
  f0x.es:
    target: foxcaves
  www.f0x.es:
    target: foxcaves
