defaults:
  ports:
    http: 80
    https: 443
aliases:
  nas:
    target: 10.2.11.1
    proxy_protocol: true
  grafana:
    target: 10.2.11.5
    proxy_protocol: true
  homeassistant:
    target: 10.2.12.2
  spaceage-web:
    target: 10.3.10.5
    proxy_protocol: true
  foxcaves:
    target: 10.3.10.1
  git:
    target: 10.3.10.2
hosts:
  __default__:
    target: host.docker.internal
    ports:
      http: 8080
      https: 8443

  # Home network
  grafana.foxden.network:
    target: grafana
  nas.foxden.network:
    target: nas
  homeassistant.foxden.network:
    target: homeassistant

  # SpaceAge
  api.spaceage.mp:
    target: spaceage-web
  tts.spaceage.mp:
    target: spaceage-web
  spaceage.mp:
    target: spaceage-website
  www.spaceage.mp:
    target: spaceage-website

  # foxCaves
  foxcav.es:
    target: foxcaves-site
  www.foxcav.es:
    target: foxcaves-site
  f0x.es:
    target: foxcaves-site
  www.f0x.es:
    target: foxcaves-site

  # Personal website
  doridian.de:
    target: website
  www.doridian.de:
    target: website
  doridian.net:
    target: website
  www.doridian.net:
    target: website

  git.foxden.network:
    target: git
