defaults:
  ports:
    http: 80
    https: 443
aliases:
  nas:
    target: 10.2.11.1
    proxy_protocol: true
  grafana:
    target: 10.2.11.5
    proxy_protocol: true
  spaceage-web:
    target: 10.3.10.5
    proxy_protocol: true
    ports:
      http: 8080
      https: 8443
  foxcaves:
    target: 10.3.10.1
    proxy_protocol: true
    ports:
      http: 8080
      https: 8443
  git:
    target: 10.3.10.2
    proxy_protocol: true
  s3:
    target: 10.2.11.17
    proxy_protocol: true
  homeassistant:
    target: 10.2.12.2
    #proxy_protocol: true
    #ports:
    #  http: 8080
    #  https: 8443
hosts:
  __default__:
    target: host.docker.internal
    ports:
      http: 8080
      https: 8443

  # Home network
  grafana.foxden.network:
    target: grafana
  nas.foxden.network:
    target: nas
  homeassistant.foxden.network:
    target: homeassistant

  # SpaceAge
  api.spaceage.mp:
    target: spaceage-web
  tts.spaceage.mp:
    target: spaceage-web
  spaceage.mp:
    target: spaceage-website # Direct host mapping
  www.spaceage.mp:
    target: spaceage-website # Direct host mapping

  # foxCaves
  foxcav.es:
    target: foxcaves
  www.foxcav.es:
    target: foxcaves
  f0x.es:
    target: foxcaves
  www.f0x.es:
    target: foxcaves

  # Personal website
  doridian.de:
    target: website # Direct host mapping
  www.doridian.de:
    target: website # Direct host mapping
  doridian.net:
    target: website # Direct host mapping
  www.doridian.net:
    target: website # Direct host mapping

  git.foxden.network:
    target: git

  s3.foxden.network:
    target: s3
  console.s3.foxden.network:
    target: s3
