defaults:
  backends:
    http:
      host: host.docker.internal
      port: 80
    https:
      host: host.docker.internal
      port: 443
templates:
  nas:
    backends:
      http:
        host: 10.2.11.1
        proxy_protocol: true
      https:
        host: 10.2.11.1
        proxy_protocol: true
  grafana:
    backends:
      http:
        host: 10.2.11.5
        proxy_protocol: true
      https:
        host: 10.2.11.5
        proxy_protocol: true
  spaceage-web:
    backends:
      http:
        host: 10.3.10.5
        proxy_protocol: true
        port: 8080
      https:
        host: 10.3.10.5
        proxy_protocol: true
        port: 8443
  foxcaves:
    backends:
      http:
        host: 10.3.10.1
        proxy_protocol: true
        port: 8080
      https:
        host: 10.3.10.1
        proxy_protocol: true
        port: 8443
  git:
    backends:
      http:
        host: 10.3.10.2
        proxy_protocol: true
      https:
        host: 10.3.10.2
        proxy_protocol: true
  s3:
    backends:
      http:
        host: 10.2.11.17
        proxy_protocol: true
      https:
        host: 10.2.11.17
        proxy_protocol: true
  homeassistant:
    backends:
      http:
        host: 10.2.12.2
        #proxy_protocol: true
        #port: 8080
      https:
        host: 10.2.12.2
        #proxy_protocol: true
        #port: 8443
  spaceage-website:
    backends:
      http:
        host: spaceage-website
      https:
        host: spaceage-website
  website:
    backends:
      http:
        host: website
      https:
        host: website

hosts:
  # Home network
  grafana.foxden.network:
    template: grafana
  nas.foxden.network:
    template: nas
  dav.foxden.network:
    template: nas
  homeassistant.foxden.network:
    template: homeassistant

  # SpaceAge
  api.spaceage.mp:
    template: spaceage-web
  tts.spaceage.mp:
    template: spaceage-web
  spaceage.mp:
    template: spaceage-website
  www.spaceage.mp:
    template: spaceage-website

  # foxCaves
  foxcav.es:
    template: foxcaves
  www.foxcav.es:
    template: foxcaves
  f0x.es:
    template: foxcaves
  www.f0x.es:
    template: foxcaves

  xmppshare.f0x.es:
    backends:
      http:
        host: prosody
        port: 80
      https:
        host: prosody
        port: 5281

  # Personal website
  doridian.de:
    template: website
  www.doridian.de:
    template: website
  doridian.net:
    template: website
  www.doridian.net:
    template: website

  git.foxden.network:
    template: git
