defaults:
  ports:
    http: 80
    https: 443
aliases:
  nas:
    target: 10.2.11.1
  grafana:
    target: 10.2.11.5
  homeassistant:
    target: 10.2.12.2
  spaceage-web:
    target: 10.3.10.5
  foxcaves:
    target: 10.3.10.1
hosts:
  __default__:
    target: host.docker.internal
    ports:
      http: 8080
      https: 8443

  # Home network
  grafana.foxden.network:
    target: grafana
  nas.foxden.network:
    target: nas
  homeassistant.foxden.network:
    target: homeassistant

  # SpaceAge
  api.spaceage.mp:
    target: spaceage-web
  spaceage.mp:
    target: spaceage-web
  static.spaceage.mp:
    target: spaceage-web
  tts.spaceage.mp:
    target: spaceage-web
  www.spaceage.mp:
    target: spaceage-web
  forums.spaceage.mp:
    target: spaceage-web

  # foxCaves
  foxcaves.foxden.network:
    target: foxcaves
  fox.ax:
    target: foxcaves
  foxcaves.fox.ax:
    target: foxcaves
  caves.fox.ax:
    target: foxcaves
  www.fox.ax:
    target: foxcaves

  # Personal website
  doridian.de:
    target: website
  www.doridian.de:
    target: website
  doridian.com:
    target: website
  www.doridian.com:
    target: website
  doridian.net:
    target: website
  www.doridian.net:
    target: website
  doridian.org:
    target: website
  www.doridian.org:
    target: website

  pawnode.com:
    target: website
  www.pawnode.com:
    target: website
  as207618.net:
    target: website
  www.as207618.net:
    target: website
